### ISSUE TITLE
Metadata v2.1

### ISSUE THREAD

**Issue by rgrp** [okfn/datacatalogs.org#34]
* [x] update database with new fields - field changes are listed in the [spreadsheet here](https://docs.google.com/a/okfn.org/spreadsheets/d/14vMXFDKwMJrHLf1zQtAt6Z6cWRRQuXFNmBx-qHDImBA/edit#gid=0)
  * author -> Renamed to publisher
  * groups -> Disappears, tags covers this
  * license -> Renamed to license_id
  * metadatamodified -> Disappears, too hard to maintain
  * New fields:
    * license_url
    * issued
    * publisher_classification
    * generator
    * api_endpoint
    * api_type
    * full_metadata_download
* [x] update submission form with relevant fields
* [x] update webapp if appropriate

Note: the field 'license_open' is still up for discussion. We will now have scope to put a page explaining the situation for mixed licenses under license_url if 'license_id' cannot be filled in or is filled in with something ambiguous. The question is whether catalogs that don't have a single license ought to have license_open set to FALSE or empty.

A further discussion topic is whether we want to have scope for generating stats on the catalogs (e.g. number of datasets, or catalog last updated) and storing them in some way.

**Comment by rgrp** [comment]
@mattfullerton would you be up for having a stab at frontend changes? Also have you started adding the metadata you had here (in particular, is the metadata structure now sufficient for your needs?)?

**Comment by mattfullerton** [comment]
> @mattfullerton would you be up for having a stab at frontend changes?

Yes, I just made a start by changing the info boxes to link to the catalogs and only show a few bits of data. When I push to Heroku though I get a bizarre dependency error with npm. Maybe you can check at your end of the current codebase pushes well to Heroku.

> Also have you started adding the metadata you had here (in particular, is the metadata structure now sufficient for your needs?)?

I haven't added it yet; I just need to write a script. Overall I'm happy with the structure but I've come across SO many instances of the full metadata not being directly accessible without writing a script to handle multiple API calls, that I would still value a field for 'metadata_dump' or something similar. But give that that might be something we want to explain in the description anyway (why is the dump coming from a 3rd party), it can also go there (as we agreed, some time ago).

**Comment by mattfullerton** [comment]
Catalog page is now done too. For a filled example see https://datacatalogsfrontendchanges.herokuapp.com/catalog/rheinland-pfalz

For an unfilled one see any other catalog :) Do we want to hide unfilled fields or highlight that we don't have/are seeking the info?

Beyond that, I haven't shown metadatacreated or metadatamodified as I assume they are mainly for internal use.

Do we want to expand country/language based on some mapping?

Can we close this issue? Requests for changes in the display could go in newer, compact issues.

**Comment by rgrp** [comment]
@mattfullerton this sounds great. Can you PR and we can deploy? Agree that we can close this and create new, more specific issues.

**Comment by mattfullerton** [comment]
It's in the master branch of the repo :)

**Comment by rgrp** [comment]
@mattfullerton perfect - deploying now (I'll also add you as a heroku collaborator so you can deploy directly!)

**Comment by rgrp** [comment]
@mattfullerton you are now added as a collaborator - do you want to try deploying yourself?

**Comment by mattfullerton** [comment]
Done/works
